name: Table of Contents
on: 
  push:
    branches:
    - master
    paths:
    - 'pages/Common-Issues.md'
    - 'pages/FAQ.md'
    - 'pages/Server-Optimizations.md'
    
jobs:
  populate:
    name: TOC Generator
    runs-on: ubuntu-latest
    steps:
      - name: TOC Generator
        uses: technote-space/toc-generator@v4.3.1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_PATHS: 'pages/Common-Issues.md,pages/FAQ.md,pages/Server-Optimizations.md'
          TOC_TITLE: '**Table of Contents**'
          COMMIT_MESSAGE: 'Updated Table of Contents'
          COMMIT_NAME: 'TheBusyBot'
          FOLDING: true
          CREATE_PR: false
          MAX_HEADER_LEVEL: 2
